exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Codename V
production_url : http://www.codenamev.com
description: "Code by Valentino Ulysses Stoll."
disqus_shortname: thecodenamev
analytics: UA-27911694-1
gauges: 
author :
  name : Valentino Ulysses Stoll
  github : codenamev
  twitter : theawesomevibe
  email: thevalentino+code@gmail.com
